import { useState } from 'react';
import { Shield, MapPin, FileCheck, Brain, Globe, TrendingUp, ArrowRight, Layers3, Users, MessageSquare, BadgeCheck, X, CheckCircle2, Landmark, Search, FileSearch, Scale } from 'lucide-react';
import { Button } from './ui/button';
import { Card, CardContent } from './ui/card';

interface LandingPageProps {
  onSignIn: () => void;
  onBrowseVerifiedLands: () => void;
  onListYourProperty: () => void;
  onExplorePlatform: () => void;
  onLearnMore: () => void;
}

export function LandingPage({
  onSignIn,
  onBrowseVerifiedLands,
  onListYourProperty,
  onExplorePlatform,
  onLearnMore,
}: LandingPageProps) {
  const [showLearnMore, setShowLearnMore] = useState(false);

  const handleLearnMore = () => {
    setShowLearnMore(true);
    onLearnMore();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-emerald-50 text-slate-900">
      {/* Navigation */}
      <nav className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex justify-between items-center">
            <div className="flex items-center gap-2">
              <Shield className="w-8 h-8 text-blue-600" />
              <span className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-green-600 bg-clip-text text-transparent">
                CM Platform
              </span>
            </div>
            <div className="flex items-center gap-3">
              <Button variant="ghost" onClick={handleLearnMore}>
                Learn More
              </Button>
              <Button variant="ghost" onClick={onSignIn}>
                Sign In
              </Button>
              <Button onClick={onExplorePlatform}>
                Get Started
              </Button>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center">
          <h1 className="text-5xl md:text-7xl mb-6 bg-gradient-to-r from-blue-600 via-green-600 to-blue-600 bg-clip-text text-transparent">
            AI-Powered Global Land
            <br />
            Verification Platform
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Buy and sell land with 100% verified documentation, AI-driven historical analysis,
            and complete legal clarity. Trusted by buyers and sellers worldwide.
          </p>
          <div className="flex gap-4 justify-center flex-wrap">
            <Button size="lg" onClick={onBrowseVerifiedLands} className="text-lg px-8">
              Browse Verified Lands
              <ArrowRight className="w-4 h-4" />
            </Button>
            <Button size="lg" variant="outline" onClick={onListYourProperty} className="text-lg px-8">
              List Your Property
            </Button>
            <Button size="lg" variant="secondary" onClick={handleLearnMore} className="text-lg px-8">
              Explore Platform
            </Button>
          </div>
          
          <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
            <div>
              <div className="text-4xl mb-2">100%</div>
              <div className="text-gray-600">Verified Documentation</div>
            </div>
            <div>
              <div className="text-4xl mb-2">30+</div>
              <div className="text-gray-600">Years History Analysis</div>
            </div>
            <div>
              <div className="text-4xl mb-2">50+</div>
              <div className="text-gray-600">Countries Supported</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <h2 className="text-4xl text-center mb-12">
          Why Choose CM Platform?
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card>
            <CardContent className="p-6">
              <Brain className="w-12 h-12 text-blue-600 mb-4" />
              <h3 className="text-xl mb-2">AI-Generated Documentation</h3>
              <p className="text-gray-600">
                Instant legal and technical documentation generated by AI based on uploaded records
                and historical data.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <MapPin className="w-12 h-12 text-green-600 mb-4" />
              <h3 className="text-xl mb-2">30+ Years Historical Analysis</h3>
              <p className="text-gray-600">
                AI analyzes satellite imagery and registry data to track land-use changes and
                ownership history.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <FileCheck className="w-12 h-12 text-purple-600 mb-4" />
              <h3 className="text-xl mb-2">Complete Legal Verification</h3>
              <p className="text-gray-600">
                Legal team verifies AI findings and ensures all documentation meets local regulations.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <Shield className="w-12 h-12 text-red-600 mb-4" />
              <h3 className="text-xl mb-2">Risk Detection</h3>
              <p className="text-gray-600">
                Automatic detection of disputes, water bodies, forests, or restricted zones on the property.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <TrendingUp className="w-12 h-12 text-orange-600 mb-4" />
              <h3 className="text-xl mb-2">Construction Feasibility</h3>
              <p className="text-gray-600">
                AI analyzes soil suitability, buildability, and provides construction recommendations.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <Globe className="w-12 h-12 text-cyan-600 mb-4" />
              <h3 className="text-xl mb-2">Global Coverage</h3>
              <p className="text-gray-600">
                Support for country-specific rules and regulations across 50+ countries worldwide.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <Layers3 className="w-12 h-12 text-sky-600 mb-4" />
              <h3 className="text-xl mb-2">Seller Tools</h3>
              <p className="text-gray-600">
                Profile management, analytics, lead tracking, and listing tools for serious sellers.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <MessageSquare className="w-12 h-12 text-emerald-600 mb-4" />
              <h3 className="text-xl mb-2">Inquiry Management</h3>
              <p className="text-gray-600">
                Track buyer conversations, respond faster, and manage the sales pipeline in one place.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <Users className="w-12 h-12 text-indigo-600 mb-4" />
              <h3 className="text-xl mb-2">Role-Based Access</h3>
              <p className="text-gray-600">
                Separate experiences for buyers, sellers, legal teams, and administrators.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Platform Overview */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Card className="border-0 shadow-lg bg-slate-950 text-white overflow-hidden">
          <CardContent className="p-8 md:p-10 grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
            <div>
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-sm mb-4">
                <BadgeCheck className="w-4 h-4" />
                Everything you need in one platform
              </div>
              <h2 className="text-3xl md:text-4xl mb-4">Land verification, sales, and due diligence in one flow.</h2>
              <p className="text-slate-300 mb-6">
                CM Platform combines AI-assisted document review, historical land analysis, seller tools,
                and lead tracking so users can move from discovery to decision with fewer delays.
              </p>
              <div className="flex flex-wrap gap-3">
                <Button variant="secondary" onClick={onBrowseVerifiedLands}>Browse as Buyer</Button>
                <Button variant="outline" onClick={onListYourProperty} className="border-white text-white hover:bg-white hover:text-slate-950">
                  Sell Land
                </Button>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              {[
                ['Verified records', 'Title, tax, and ownership checks'],
                ['AI summaries', 'Risk, feasibility, and context'],
                ['Seller CRM', 'Profiles, analytics, and leads'],
                ['Messaging', 'Inquiry threads and follow-ups'],
              ].map(([title, text]) => (
                <div key={title} className="rounded-2xl border border-white/10 bg-white/5 p-4">
                  <div className="font-semibold mb-1">{title}</div>
                  <div className="text-sm text-slate-300">{text}</div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </section>

      {showLearnMore && (
        <section id="about-land-verification" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <Card className="border-slate-200 shadow-xl bg-white">
            <CardContent className="p-8 md:p-10">
              <div className="flex items-start justify-between gap-4 mb-8">
                <div>
                  <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-sm mb-4">
                    <BadgeCheck className="w-4 h-4" />
                    About Land Verification
                  </div>
                  <h2 className="text-3xl md:text-4xl mb-3">What the platform verifies before a transaction</h2>
                  <p className="text-gray-600 max-w-3xl">
                    CM Platform checks the documents, land history, and legal risks tied to a parcel so buyers and sellers can make decisions with clearer evidence and fewer surprises.
                  </p>
                </div>
                <Button variant="ghost" size="icon" onClick={() => setShowLearnMore(false)} aria-label="Close about section">
                  <X className="w-5 h-5" />
                </Button>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <Card className="border-slate-200">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-3 mb-4">
                      <Search className="w-6 h-6 text-blue-600" />
                      <h3 className="text-xl">Core verification keypoints</h3>
                    </div>
                    <div className="space-y-4 text-sm text-gray-700">
                      <div className="flex gap-3">
                        <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                        <div><span className="font-medium text-gray-900">Ownership check:</span> confirms the seller has the right to list the land.</div>
                      </div>
                      <div className="flex gap-3">
                        <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                        <div><span className="font-medium text-gray-900">Title and deed review:</span> reviews registration, title transfers, and document consistency.</div>
                      </div>
                      <div className="flex gap-3">
                        <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                        <div><span className="font-medium text-gray-900">Legal dispute screening:</span> flags claims, liens, court issues, or inheritance conflicts.</div>
                      </div>
                      <div className="flex gap-3">
                        <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                        <div><span className="font-medium text-gray-900">Land-use history:</span> compares satellite and registry records across time.</div>
                      </div>
                      <div className="flex gap-3">
                        <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                        <div><span className="font-medium text-gray-900">Zoning and buildability:</span> checks what the land can legally be used for.</div>
                      </div>
                    </div>
                  </CardContent>
                </Card>

                <Card className="border-slate-200">
                  <CardContent className="p-6">
                    <div className="flex items-center gap-3 mb-4">
                      <Landmark className="w-6 h-6 text-green-600" />
                      <h3 className="text-xl">What users get from it</h3>
                    </div>
                    <div className="space-y-4 text-sm text-gray-700">
                      <div className="flex gap-3">
                        <FileSearch className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
                        <div><span className="font-medium text-gray-900">Verified documentation:</span> a clearer record of supporting files and missing pieces.</div>
                      </div>
                      <div className="flex gap-3">
                        <Scale className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
                        <div><span className="font-medium text-gray-900">Risk summary:</span> highlights legal, environmental, and access issues before a deal closes.</div>
                      </div>
                      <div className="flex gap-3">
                        <TrendingUp className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
                        <div><span className="font-medium text-gray-900">Construction insight:</span> shows feasibility and land suitability for future use.</div>
                      </div>
                      <div className="flex gap-3">
                        <Globe className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
                        <div><span className="font-medium text-gray-900">Global support:</span> adaptable to local rules across many regions and countries.</div>
                      </div>
                      <div className="flex gap-3">
                        <FileCheck className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
                        <div><span className="font-medium text-gray-900">Human + AI workflow:</span> AI pre-checks the file set, then legal or survey teams confirm the final result.</div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>

              <div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4">
                <Card className="border-slate-200 bg-slate-50">
                  <CardContent className="p-5">
                    <h4 className="font-semibold mb-2">For buyers</h4>
                    <p className="text-sm text-gray-600">Know what is verified, what is risky, and what still needs review before making an offer.</p>
                  </CardContent>
                </Card>
                <Card className="border-slate-200 bg-slate-50">
                  <CardContent className="p-5">
                    <h4 className="font-semibold mb-2">For sellers</h4>
                    <p className="text-sm text-gray-600">Show proof faster, build trust, and reduce back-and-forth with better documentation.</p>
                  </CardContent>
                </Card>
                <Card className="border-slate-200 bg-slate-50">
                  <CardContent className="p-5">
                    <h4 className="font-semibold mb-2">For legal teams</h4>
                    <p className="text-sm text-gray-600">Review exceptions, confirm compliance, and close cases with a traceable workflow.</p>
                  </CardContent>
                </Card>
              </div>

              <div className="mt-8 flex flex-wrap gap-3">
                <Button onClick={onBrowseVerifiedLands}>Browse verified lands</Button>
                <Button variant="outline" onClick={onListYourProperty}>List your property</Button>
                <Button variant="secondary" onClick={onSignIn}>Sign in to continue</Button>
              </div>
            </CardContent>
          </Card>
        </section>
      )}

      {/* How It Works */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <h2 className="text-4xl text-center mb-12">
          How It Works
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="w-16 h-16 bg-blue-600 text-white rounded-full flex items-center justify-center text-2xl mx-auto mb-4">
              1
            </div>
            <h3 className="text-xl mb-2">Upload & Verify</h3>
            <p className="text-gray-600">
              Seller uploads land documents. AI performs instant analysis and verification.
            </p>
          </div>

          <div className="text-center">
            <div className="w-16 h-16 bg-green-600 text-white rounded-full flex items-center justify-center text-2xl mx-auto mb-4">
              2
            </div>
            <h3 className="text-xl mb-2">Survey & Assess</h3>
            <p className="text-gray-600">
              Survey team confirms physical status. AI generates construction feasibility report.
            </p>
          </div>

          <div className="text-center">
            <div className="w-16 h-16 bg-purple-600 text-white rounded-full flex items-center justify-center text-2xl mx-auto mb-4">
              3
            </div>
            <h3 className="text-xl mb-2">Buy with Confidence</h3>
            <p className="text-gray-600">
              Buyer reviews verified land. AI assists with legal closure and documentation.
            </p>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <Card className="bg-gradient-to-r from-blue-600 to-green-600 border-0">
          <CardContent className="p-12 text-center text-white">
            <h2 className="text-4xl mb-4">
              Ready to Get Started?
            </h2>
            <p className="text-xl mb-8 opacity-90">
              Join thousands of buyers and sellers who trust CM Platform for safe land transactions.
            </p>
            <div className="flex gap-4 justify-center flex-wrap">
              <Button size="lg" variant="secondary" onClick={() => onLogin('buyer')} className="text-lg px-8">
                Start as Buyer
              </Button>
              <Button size="lg" variant="outline" onClick={() => onLogin('seller')} className="text-lg px-8 bg-white/10 border-white text-white hover:bg-white/20">
                Start as Seller
              </Button>
            </div>
          </CardContent>
        </Card>
      </section>

      {/* Footer */}
      <footer className="border-t bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <Shield className="w-6 h-6 text-blue-600" />
                <span className="font-bold">CM Platform</span>
              </div>
              <p className="text-gray-600 text-sm">
                AI-powered global land verification and real estate platform.
              </p>
            </div>
            <div>
              <h4 className="mb-4">Platform</h4>
              <ul className="space-y-2 text-sm text-gray-600">
                <li>Buy Land</li>
                <li>Sell Land</li>
                <li>Legal Services</li>
                <li>Survey Services</li>
              </ul>
            </div>
            <div>
              <h4 className="mb-4">Company</h4>
              <ul className="space-y-2 text-sm text-gray-600">
                <li>About Us</li>
                <li>How It Works</li>
                <li>Pricing</li>
                <li>Contact</li>
              </ul>
            </div>
            <div>
              <h4 className="mb-4">Legal</h4>
              <ul className="space-y-2 text-sm text-gray-600">
                <li>Privacy Policy</li>
                <li>Terms of Service</li>
                <li>Cookie Policy</li>
                <li>Compliance</li>
              </ul>
            </div>
          </div>
          <div className="border-t mt-8 pt-8 text-center text-sm text-gray-600">
            © 2026 CM Platform. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
}
