import { Shield, MapPin, FileCheck, Brain, Globe, TrendingUp } from 'lucide-react';
import { Button } from './ui/button';
import { Card, CardContent } from './ui/card';
import { UserRole } from '../App';

interface LandingPageProps {
  onLogin: (role: UserRole) => void;
}

export function LandingPage({ onLogin }: LandingPageProps) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-green-50">
      {/* Navigation */}
      <nav className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex justify-between items-center">
            <div className="flex items-center gap-2">
              <Shield className="w-8 h-8 text-blue-600" />
              <span className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-green-600 bg-clip-text text-transparent">
                CM Platform
              </span>
            </div>
            <div className="flex gap-3">
              <Button variant="ghost" onClick={() => onLogin('buyer')}>
                Sign In
              </Button>
              <Button onClick={() => onLogin('seller')}>
                Get Started
              </Button>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center">
          <h1 className="text-5xl md:text-7xl mb-6 bg-gradient-to-r from-blue-600 via-green-600 to-blue-600 bg-clip-text text-transparent">
            AI-Powered Global Land
            <br />
            Verification Platform
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Buy and sell land with 100% verified documentation, AI-driven historical analysis,
            and complete legal clarity. Trusted by buyers and sellers worldwide.
          </p>
          <div className="flex gap-4 justify-center flex-wrap">
            <Button size="lg" onClick={() => onLogin('buyer')} className="text-lg px-8">
              Browse Verified Lands
            </Button>
            <Button size="lg" variant="outline" onClick={() => onLogin('seller')} className="text-lg px-8">
              List Your Property
            </Button>
          </div>
          
          <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
            <div>
              <div className="text-4xl mb-2">100%</div>
              <div className="text-gray-600">Verified Documentation</div>
            </div>
            <div>
              <div className="text-4xl mb-2">30+</div>
              <div className="text-gray-600">Years History Analysis</div>
            </div>
            <div>
              <div className="text-4xl mb-2">50+</div>
              <div className="text-gray-600">Countries Supported</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <h2 className="text-4xl text-center mb-12">
          Why Choose CM Platform?
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card>
            <CardContent className="p-6">
              <Brain className="w-12 h-12 text-blue-600 mb-4" />
              <h3 className="text-xl mb-2">AI-Generated Documentation</h3>
              <p className="text-gray-600">
                Instant legal and technical documentation generated by AI based on uploaded records
                and historical data.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <MapPin className="w-12 h-12 text-green-600 mb-4" />
              <h3 className="text-xl mb-2">30+ Years Historical Analysis</h3>
              <p className="text-gray-600">
                AI analyzes satellite imagery and registry data to track land-use changes and
                ownership history.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <FileCheck className="w-12 h-12 text-purple-600 mb-4" />
              <h3 className="text-xl mb-2">Complete Legal Verification</h3>
              <p className="text-gray-600">
                Legal team verifies AI findings and ensures all documentation meets local regulations.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <Shield className="w-12 h-12 text-red-600 mb-4" />
              <h3 className="text-xl mb-2">Risk Detection</h3>
              <p className="text-gray-600">
                Automatic detection of disputes, water bodies, forests, or restricted zones on the property.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <TrendingUp className="w-12 h-12 text-orange-600 mb-4" />
              <h3 className="text-xl mb-2">Construction Feasibility</h3>
              <p className="text-gray-600">
                AI analyzes soil suitability, buildability, and provides construction recommendations.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <Globe className="w-12 h-12 text-cyan-600 mb-4" />
              <h3 className="text-xl mb-2">Global Coverage</h3>
              <p className="text-gray-600">
                Support for country-specific rules and regulations across 50+ countries worldwide.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* How It Works */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <h2 className="text-4xl text-center mb-12">
          How It Works
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="w-16 h-16 bg-blue-600 text-white rounded-full flex items-center justify-center text-2xl mx-auto mb-4">
              1
            </div>
            <h3 className="text-xl mb-2">Upload & Verify</h3>
            <p className="text-gray-600">
              Seller uploads land documents. AI performs instant analysis and verification.
            </p>
          </div>

          <div className="text-center">
            <div className="w-16 h-16 bg-green-600 text-white rounded-full flex items-center justify-center text-2xl mx-auto mb-4">
              2
            </div>
            <h3 className="text-xl mb-2">Survey & Assess</h3>
            <p className="text-gray-600">
              Survey team confirms physical status. AI generates construction feasibility report.
            </p>
          </div>

          <div className="text-center">
            <div className="w-16 h-16 bg-purple-600 text-white rounded-full flex items-center justify-center text-2xl mx-auto mb-4">
              3
            </div>
            <h3 className="text-xl mb-2">Buy with Confidence</h3>
            <p className="text-gray-600">
              Buyer reviews verified land. AI assists with legal closure and documentation.
            </p>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <Card className="bg-gradient-to-r from-blue-600 to-green-600 border-0">
          <CardContent className="p-12 text-center text-white">
            <h2 className="text-4xl mb-4">
              Ready to Get Started?
            </h2>
            <p className="text-xl mb-8 opacity-90">
              Join thousands of buyers and sellers who trust CM Platform for safe land transactions.
            </p>
            <div className="flex gap-4 justify-center flex-wrap">
              <Button size="lg" variant="secondary" onClick={() => onLogin('buyer')} className="text-lg px-8">
                Start as Buyer
              </Button>
              <Button size="lg" variant="outline" onClick={() => onLogin('seller')} className="text-lg px-8 bg-white/10 border-white text-white hover:bg-white/20">
                Start as Seller
              </Button>
            </div>
          </CardContent>
        </Card>
      </section>

      {/* Footer */}
      <footer className="border-t bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <Shield className="w-6 h-6 text-blue-600" />
                <span className="font-bold">CM Platform</span>
              </div>
              <p className="text-gray-600 text-sm">
                AI-powered global land verification and real estate platform.
              </p>
            </div>
            <div>
              <h4 className="mb-4">Platform</h4>
              <ul className="space-y-2 text-sm text-gray-600">
                <li>Buy Land</li>
                <li>Sell Land</li>
                <li>Legal Services</li>
                <li>Survey Services</li>
              </ul>
            </div>
            <div>
              <h4 className="mb-4">Company</h4>
              <ul className="space-y-2 text-sm text-gray-600">
                <li>About Us</li>
                <li>How It Works</li>
                <li>Pricing</li>
                <li>Contact</li>
              </ul>
            </div>
            <div>
              <h4 className="mb-4">Legal</h4>
              <ul className="space-y-2 text-sm text-gray-600">
                <li>Privacy Policy</li>
                <li>Terms of Service</li>
                <li>Cookie Policy</li>
                <li>Compliance</li>
              </ul>
            </div>
          </div>
          <div className="border-t mt-8 pt-8 text-center text-sm text-gray-600">
            © 2026 CM Platform. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
}
