import { useState } from 'react';
import { Button } from './ui/button';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Download, FileText, CheckCircle, AlertCircle, Clock } from 'lucide-react';
import { User } from '../App';

interface ViewDocumentsProps {
  user: User;
  onLogout: () => void;
  onBack: () => void;
}

export function ViewDocuments({ user, onLogout, onBack }: ViewDocumentsProps) {
  const [downloading, setDownloading] = useState<string | null>(null);

  const documentRequirements = [
    {
      category: 'Essential Documents',
      required: true,
      documents: [
        {
          name: 'Title Deed / Ownership Certificate',
          description: 'Original property ownership document issued by the government',
          status: 'required',
          importance: 'Critical'
        },
        {
          name: 'Land Survey Report',
          description: 'Recent survey report showing exact boundaries and measurements',
          status: 'required',
          importance: 'Critical'
        },
        {
          name: 'Tax Records',
          description: 'Property tax payment records for the last 5 years',
          status: 'required',
          importance: 'High'
        },
        {
          name: 'Zoning Compliance Certificate',
          description: 'Certificate confirming land use complies with local zoning laws',
          status: 'required',
          importance: 'High'
        }
      ]
    },
    {
      category: 'Additional Documents',
      required: false,
      documents: [
        {
          name: 'Soil Analysis Report',
          description: 'Geotechnical report on soil composition and bearing capacity',
          status: 'recommended',
          importance: 'Medium'
        },
        {
          name: 'Water Rights Certificate',
          description: 'Rights to use water from wells, rivers, or municipal sources',
          status: 'recommended',
          importance: 'Medium'
        },
        {
          name: 'Environmental Clearance',
          description: 'Environmental impact assessment and clearance certificate',
          status: 'recommended',
          importance: 'Medium'
        },
        {
          name: 'Building Permits',
          description: 'Any existing or previous building permits for the property',
          status: 'optional',
          importance: 'Low'
        }
      ]
    },
    {
      category: 'Legal Documents',
      required: false,
      documents: [
        {
          name: 'Encumbrance Certificate',
          description: 'Certificate showing any mortgages, liens, or legal claims',
          status: 'recommended',
          importance: 'High'
        },
        {
          name: 'Non-Encumbrance Certificate',
          description: 'Certificate confirming no legal encumbrances on the property',
          status: 'recommended',
          importance: 'High'
        },
        {
          name: 'Court Orders',
          description: 'Any court orders or legal judgments affecting the property',
          status: 'optional',
          importance: 'Medium'
        }
      ]
    }
  ];

  const generatePDF = async (documentName: string) => {
    setDownloading(documentName);

    // Simulate PDF generation
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Create a simple PDF-like content (in a real app, use a PDF library)
    const content = `
LAND DOCUMENTATION REQUIREMENTS
================================

${documentRequirements.map(category => `
${category.category.toUpperCase()}
${'='.repeat(category.category.length)}

${category.documents.map(doc => `
${doc.name}
${'-'.repeat(doc.name.length)}
Description: ${doc.description}
Status: ${doc.status}
Importance: ${doc.importance}

`).join('')}
`).join('')}

Generated by CM Platform
Date: ${new Date().toLocaleDateString()}
User: ${user.name}
    `.trim();

    // Create and download the file
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${documentName.replace(/\s+/g, '_').toLowerCase()}_requirements.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setDownloading(null);
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'required':
        return <AlertCircle className="w-4 h-4 text-red-500" />;
      case 'recommended':
        return <Clock className="w-4 h-4 text-yellow-500" />;
      case 'optional':
        return <CheckCircle className="w-4 h-4 text-green-500" />;
      default:
        return null;
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'required':
        return 'bg-red-100 text-red-800';
      case 'recommended':
        return 'bg-yellow-100 text-yellow-800';
      case 'optional':
        return 'bg-green-100 text-green-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const getImportanceColor = (importance: string) => {
    switch (importance) {
      case 'Critical':
        return 'bg-red-100 text-red-800';
      case 'High':
        return 'bg-orange-100 text-orange-800';
      case 'Medium':
        return 'bg-yellow-100 text-yellow-800';
      case 'Low':
        return 'bg-green-100 text-green-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Navigation */}
      <nav className="border-b bg-white sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex justify-between items-center">
            <div className="flex items-center gap-6">
              <div className="flex items-center gap-2">
                <FileText className="w-6 h-6 text-blue-600" />
                <span className="text-xl font-bold">View Documents</span>
              </div>
              <Button variant="ghost" onClick={onBack}>
                ← Back to Dashboard
              </Button>
            </div>
            <div className="flex items-center gap-3">
              <div className="text-sm">
                <div>{user.name}</div>
                <div className="text-gray-500 text-xs capitalize">{user.role}</div>
              </div>
              <Button variant="ghost" size="sm" onClick={onLogout}>
                Logout
              </Button>
            </div>
          </div>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-3xl mb-2">Land Documentation Requirements</h1>
          <p className="text-gray-600">
            Complete guide to all documents required for land verification and property transactions.
          </p>
        </div>

        {/* Download Section */}
        <Card className="mb-8">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-xl font-semibold mb-2">Download Complete Requirements Guide</h2>
                <p className="text-gray-600">
                  Get a comprehensive PDF guide with all documentation requirements and checklists.
                </p>
              </div>
              <Button
                onClick={() => generatePDF('Land_Documentation_Requirements')}
                disabled={downloading !== null}
                className="flex items-center gap-2"
              >
                <Download className="w-4 h-4" />
                {downloading === 'Land_Documentation_Requirements' ? 'Generating...' : 'Download PDF'}
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Document Categories */}
        <div className="space-y-6">
          {documentRequirements.map((category, categoryIndex) => (
            <Card key={categoryIndex}>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  {category.category}
                  {category.required && (
                    <Badge variant="destructive">Required</Badge>
                  )}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {category.documents.map((doc, docIndex) => (
                    <div key={docIndex} className="border rounded-lg p-4 hover:bg-gray-50 transition-colors">
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-2">
                            {getStatusIcon(doc.status)}
                            <h3 className="font-semibold">{doc.name}</h3>
                            <Badge className={getStatusColor(doc.status)}>
                              {doc.status}
                            </Badge>
                            <Badge className={getImportanceColor(doc.importance)}>
                              {doc.importance}
                            </Badge>
                          </div>
                          <p className="text-gray-600 text-sm mb-3">{doc.description}</p>
                        </div>
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => generatePDF(doc.name)}
                          disabled={downloading !== null}
                        >
                          {downloading === doc.name ? (
                            'Generating...'
                          ) : (
                            <>
                              <Download className="w-3 h-3 mr-1" />
                              Info
                            </>
                          )}
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Additional Information */}
        <Card className="mt-8">
          <CardHeader>
            <CardTitle>Important Notes</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3 text-sm text-gray-600">
              <p>
                <strong>Document Validity:</strong> All documents should be recent (within the last 6-12 months)
                unless specified otherwise.
              </p>
              <p>
                <strong>Original vs Copies:</strong> Original documents are preferred, but certified copies
                may be accepted in some cases.
              </p>
              <p>
                <strong>Language:</strong> Documents in local language may need to be translated and
                notarized for international transactions.
              </p>
              <p>
                <strong>Verification Time:</strong> Complete document verification typically takes
                3-5 business days.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
